const { SlashCommandBuilder, ApplicationIntegrationType, InteractionContextType, EmbedBuilder } = require('discord.js');
const KeyService = require('../../src/services/KeyService');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('generate')
        .setDescription('Generate a 1-day whitelist license key (Limit: 1 key per user)')
        .setIntegrationTypes([ApplicationIntegrationType.GuildInstall])
        .setContexts([InteractionContextType.Guild]),

    async execute(interaction) {
        const discordId = interaction.user.id;

        // 1. Check if user already owns an active key (limit: max 1 key)
        const existingKey = KeyService.checkUserKey(discordId);
        if (existingKey) {
            const expireText = existingKey.expiresAt
                ? `<t:${Math.floor(new Date(existingKey.expiresAt).getTime() / 1000)}:R>`
                : 'Never';

            const limitEmbed = new EmbedBuilder()
                .setColor(0xef4444)
                .setTitle('⚠️ Key Generation Limit Exceeded')
                .setDescription(`You already have an active license key. You cannot generate more than 1 active key at a time.`)
                .addFields(
                    { name: 'Active Key Identifier', value: `\`${existingKey.keyPrefix}\``, inline: true },
                    { name: 'Tier', value: `\`${existingKey.tier.toUpperCase()}\``, inline: true },
                    { name: 'Expires', value: expireText, inline: true },
                    { name: 'Device Bindings', value: `${existingKey.bindingsCount} / ${existingKey.maxClients}`, inline: true }
                )
                .setFooter({ text: 'Wait until your current key expires to generate a new one, or check /checkkey.' })
                .setTimestamp();

            return interaction.reply({
                embeds: [limitEmbed],
                ephemeral: true
            });
        }

        // 2. Generate 1-day key linked to the user
        const durationDays = 1;
        const { plainKey, keyRecord } = KeyService.createKey({
            tier: 'premium',
            durationDays,
            maxClients: 1,
            discordId,
            createdBy: `Discord:${discordId}`,
            note: `Daily key generated by ${interaction.user.tag} (${discordId})`
        });

        const expireTimestamp = Math.floor(new Date(keyRecord.expiresAt).getTime() / 1000);

        const successEmbed = new EmbedBuilder()
            .setColor(0x10b981)
            .setTitle('🎉 1-Day License Key Generated')
            .setDescription(`Your temporary 1-day whitelist license key has been generated and bound to your account.\n\n⚠️ **Copy this key now!** It is hashed on the server and will not be displayed in plaintext again.`)
            .addFields(
                { name: '🔑 License Key', value: `\`\`\`${plainKey}\`\`\`` },
                { name: 'Tier', value: `\`${keyRecord.tier.toUpperCase()}\``, inline: true },
                { name: 'Duration', value: '1 Day (24 Hours)', inline: true },
                { name: 'Expires', value: `<t:${expireTimestamp}:R> (<t:${expireTimestamp}:f>)`, inline: true },
                { name: 'Max Devices', value: `${keyRecord.maxClients} Device`, inline: true }
            )
            .setFooter({ text: 'Paste this key into Initialize.lua under CONFIG.UserKey to execute the script.' })
            .setTimestamp();

        await interaction.reply({
            embeds: [successEmbed],
            ephemeral: true
        });
    }
};
